bootstrapServers: localhost:29092
chargingEventsTopicName: charging-event
appId: streams-app-232332132k
schemaRegistryUrl: http://localhost:8090
server:
  applicationConnectors:
    - type: http
      port: 9000
  adminConnectors:
    - type: http
      port: 9001
database:
  driverClass: org.postgresql.Driver
  user: postgres
  password: secret
  url: "jdbc:postgresql://0.0.0.0:5432/postgres"
